if [ -f /etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh ]; then
  . /etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh
fi

if [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

if [ -f "$HOME/.config/zsh/mise.zsh" ]; then
  . "$HOME/.config/zsh/mise.zsh"
fi
